version: '3.8'

services:
  user_service:
    build: ./user_service
    ports:
      - "5001:5001"
    networks:
      - microservices_network
    volumes:
      - ./user_service/user_service_swagger.yml:/app/user_service_swagger.yml:ro

  watch_history_service:
    build: ./watch_history_service
    ports:
      - "5002:5002"
    networks:
      - microservices_network
    depends_on:
      - user_service
      - movie_service
    volumes:
      - ./watch_history_service/watch_service_swagger.yml:/app/watch_service_swagger.yml:ro

  rating_service:
    build: ./rating_service
    ports:
      - "5003:5003"
    networks:
      - microservices_network
    depends_on:
      - user_service
      - movie_service
    volumes:
      - ./rating_service/rating_service_swagger.yml:/app/rating_service_swagger.yml:ro

  recommendation_service:
    build: ./recommendation_service
    ports:
      - "5004:5004"
    networks:
      - microservices_network
    depends_on:
      - user_service
      - watch_history_service
      - rating_service
      - movie_service
    volumes:
      - ./recommendation_service/recommendation_service_swagger.yml:/app/recommendation_service_swagger.yml:ro

  newsfeed_service:
    build: ./newsfeed_service
    ports:
      - "5005:5005"
    networks:
      - microservices_network
    depends_on:
      - user_service
      - watch_history_service
      - movie_service
    volumes:
      - ./newsfeed_service/newsfeed_service_swagger.yml:/app/newsfeed_service_swagger.yml:ro

  movie_service:
    build: ./movie_service
    ports:
      - "5006:5006"
    networks:
      - microservices_network
    volumes:
      - ./movie_service/Top_10000_Movies_IMDb.csv:/app/Top_10000_Movies_IMDb.csv
      - ./movie_service/movie_service_swagger.yml:/app/movie_service_swagger.yml:ro

networks:
  microservices_network:
    driver: bridge